"""Response generator with context-aware answers using passage content."""

import re
from typing import List, Dict
from collections import Counter
from .registry import AgentRegistry


PHILOSOPHER_STYLES = {
    'filosofia': {
        'greeting': 'philosopher and seeker of wisdom',
        'method': 'distinguished by a commitment to rational inquiry and dialectical exchange'
    }
}


def get_philosopher_name(text: str) -> str:
    philosophers = ['Plato', 'Aristotle', 'Socrates', 'Descartes', 'Kant', 'Nietzsche',
                    'Hegel', 'Heidegger', 'Husserl', 'Foucault', 'Deleuze', 'Leibniz',
                    'Fichte', 'Russell', 'Wittgenstein']
    for p in philosophers:
        if p.lower() in text.lower():
            return p
    return ''


class ResponseGenerator:
    """Generates philosophical responses with source citations, using actual passage content."""

    def __init__(self, registry: AgentRegistry):
        self.registry = registry

    def generate(self, question: str, class_label: str,
                 passages_with_sources: List[Dict],
                 philosopher: str = 'filosofia') -> str:
        expert = self.registry.get(philosopher)
        persona = expert.get_persona()
        style = persona.split('Sei ')[-1].split('.')[0] if 'Sei ' in persona else 'Socrates'

        lines = []
        lines.append(f"[Response in the style of {style}]")
        lines.append("")
        lines.append(f"On the question: \"{question}\"")
        lines.append("")

        if class_label == 'definition':
            lines.append("Let us examine what this concept truly means. "
                         "Through careful reasoning, we can discern its essential nature.")
        elif class_label == 'comparison':
            lines.append("A comparison reveals important distinctions. "
                         "Let us consider each perspective in turn.")
        elif class_label == 'example':
            lines.append("Examples illuminate abstract ideas. "
                         "Consider the following illustration.")
        elif class_label == 'deepening':
            lines.append("This question invites deeper analysis. "
                         "Let us explore its philosophical implications.")
        elif class_label == 'quiz':
            lines.append("A thoughtful question! Let me share some insights "
                         "that might help you reflect on this topic.")
        else:
            lines.append("An interesting philosophical inquiry.")

        body = self._build_body(question, class_label, passages_with_sources)
        lines.append(body)
        lines.append("")

        if passages_with_sources:
            lines.append("Relevant passages from the philosophical corpus:")
            for i, item in enumerate(passages_with_sources, 1):
                source_info = []
                if item['source'].get('philosopher', 'Unknown') != 'Unknown':
                    source_info.append(item['source']['philosopher'])
                if item['source'].get('work', 'Unknown') != 'Unknown':
                    source_info.append(f"in \"{item['source']['work']}\"")
                tag = f" ({', '.join(source_info)})" if source_info else ""
                passage_text = item['text'][:250]
                lines.append(f"  [{i}]{tag}")
                lines.append(f"     \"{passage_text}...\"")
            lines.append("")

        lines.append("In conclusion, the philosophical tradition offers multiple lenses "
                     "through which to view this question. The passages above provide "
                     "a foundation for continued reflection and discussion.")
        lines.append("")
        lines.append("[Response generated by PhiloMind pipeline. "
                     "Full LLM integration would provide a richer, more nuanced answer.]")

        return '\n'.join(lines)

    def _build_body(self, question: str, class_label: str,
                    passages: List[Dict]) -> str:
        if not passages:
            return "I reflect on your question, though I find no direct passages in the corpus to draw upon."

        passage_texts = [p['text'] for p in passages]
        source_philosophers = list(dict.fromkeys(
            p['source'].get('philosopher', '') for p in passages
            if p['source'].get('philosopher', 'Unknown') not in ('Unknown', '')
        ))

        q_lower = question.lower()
        q_philosopher = get_philosopher_name(q_lower)

        if q_philosopher and q_philosopher in source_philosophers:
            phil_match = q_philosopher
        elif source_philosophers:
            phil_match = source_philosophers[0]
        else:
            phil_match = 'various thinkers'

        best_passage = passages[0]['text']
        best_phrases = self._extract_meaningful_phrases(best_passage, 2)

        if class_label == 'definition':
            if phras := ', '.join(best_phrases):
                return (
                    f"To understand this concept, we can turn to the work of {phil_match}. "
                    f"The philosophical tradition engages with it in terms of {phras}. "
                    f"As {phil_match} demonstrates, this question invites us to examine "
                    f"the foundational assumptions that underlie our understanding."
                )
        elif class_label == 'comparison':
            others = ', '.join(source_philosophers[:3]) if len(source_philosophers) > 1 else f'other thinkers'
            phras = ', '.join(best_phrases)
            return (
                f"The contrast between different philosophical positions is illuminating. "
                f"{' and '.join(source_philosophers[:2])} each approach the question of "
                f"{phras} from distinct perspectives. A comparison reveals how philosophical "
                f"systems differ in their starting assumptions and conclusions."
            )
        elif class_label == 'indepth':
            phras = ', '.join(best_phrases)
            return (
                f"A deeper examination guided by {phil_match} reveals that "
                f"this question touches on fundamental issues of {phras}. "
                f"The philosophical investigation goes beyond surface-level answers "
                f"to explore the underlying structures of thought."
            )
        elif class_label == 'example':
            phras = ', '.join(best_phrases)
            return (
                f"Concrete examples from {phil_match} help illustrate this point. "
                f"The discussion of {phras} shows how abstract philosophical ideas "
                f"manifest in specific cases and arguments."
            )

        phras = ', '.join(best_phrases) if best_phrases else 'philosophical concepts'
        return (
            f"This inquiry connects to broader themes explored by {phil_match}, "
            f"particularly regarding {phras}. Philosophical reflection on this topic "
            f"invites us to examine our assumptions."
        )

    def _extract_meaningful_phrases(self, text: str, n: int = 2) -> List[str]:
        sentences = re.split(r'[.!?]+', text)
        meaningful = []
        for sent in sentences:
            sent = sent.strip()
            if len(sent) < 20:
                continue
            words = sent.split()
            for i, w in enumerate(words):
                if w[0].isupper() and len(w) > 6 and i < len(words) - 1:
                    phrase = ' '.join(words[i:i+3])
                    if phrase not in meaningful:
                        meaningful.append(phrase)
        if not meaningful and sentences:
            first = sentences[0].strip()
            words = first.split()
            if len(words) > 5:
                meaningful.append(' '.join(words[:5]))
            elif first:
                meaningful.append(first[:60])
        return meaningful[:n]
