"""Response generator using actual passage content with source citations."""

import re
from typing import List, Dict
from .registry import AgentRegistry


PHILOSOPHER_NAMES = [
    'Plato', 'Aristotle', 'Socrates', 'Descartes', 'Kant', 'Nietzsche',
    'Hegel', 'Heidegger', 'Husserl', 'Foucault', 'Deleuze', 'Leibniz',
    'Fichte', 'Russell', 'Wittgenstein', 'Spinoza', 'Hume', 'Locke',
    'Rousseau', 'Marx', 'Kierkegaard', 'Sartre', 'Arendt', 'Rawls',
    'Habermas', 'Adorno', 'Derrida', 'Bacon', 'Hobbes', 'Berkeley',
]


def _find_philosopher(text: str) -> str:
    for p in PHILOSOPHER_NAMES:
        if p.lower() in text.lower():
            return p
    return ''


def _extract_sentences(text: str) -> List[str]:
    return [s.strip() for s in re.split(r'(?<=[.!?])\s+', text) if len(s.strip()) > 20]


def _summarize_passage(text: str, max_words: int = 45) -> str:
    """Extract the most contentful, self-contained sentence from a passage."""
    sentences = _extract_sentences(text)
    if not sentences:
        words = text.split()
        return ' '.join(words[:max_words]) + '...' if len(words) > max_words else text

    def score(s):
        wc = len(s.split())
        caps = sum(1 for w in re.findall(r'\b[A-Z][a-z]+\b', s))
        # penalise sentence fragments, very long or short sentences
        if wc < 6 or wc > 60:
            return 0
        return caps * 3 + wc * 0.5 - abs(wc - 20)

    candidates = sorted(sentences, key=score, reverse=True)
    best = candidates[0] if candidates else sentences[0]

    # clean up garbage characters
    best = best.replace('  ', ' ').replace(' ,', ',').replace(' .', '.')
    best = best.replace('.e.', 'i.e.').replace('.e ,', 'i.e.,')

    words = best.split()
    if len(words) > max_words:
        # truncate at last complete sentence boundary within limit
        truncated = ' '.join(words[:max_words])
        # try to end at a sentence boundary
        last_period = truncated.rfind('.')
        if last_period > len(truncated) * 0.6:
            truncated = truncated[:last_period + 1]
        elif not truncated.endswith('.'):
            truncated += '...'
        return truncated
    return best


def _passage_to_citation(item: Dict) -> str:
    """Format a passage as a readable citation with key insight."""
    src = item['source']
    phil = src.get('philosopher', '')
    work = src.get('work', '')
    insight = _summarize_passage(item['text'])

    parts = []
    if phil:
        parts.append(phil)
    if work:
        parts.append(f'in "{work}"')
    citation = f'({" — ".join(parts)})' if parts else ''

    return f'- {insight} {citation}'.strip()


class ResponseGenerator:
    """Generates responses by synthesising retrieved passage content."""

    def __init__(self, registry: AgentRegistry):
        self.registry = registry

    def generate(self, question: str, class_label: str,
                 passages_with_sources: List[Dict],
                 philosopher: str = 'filosofia') -> str:
        expert = self.registry.get(philosopher)
        persona = expert.get_persona()
        style = persona.split('Sei ')[-1].split('.')[0] if 'Sei ' in persona else 'Socrates'

        lines = []
        lines.append(f"[Response in the style of {style}]")
        lines.append("")
        lines.append(f"On the question: \"{question}\"")
        lines.append("")

        # -- Body: synthesize passages --
        body = self._build_body(question, class_label, passages_with_sources)
        lines.append(body)
        lines.append("")

        # -- Citations --
        if passages_with_sources:
            lines.append("Key passages from the philosophical corpus:")
            for item in passages_with_sources:
                lines.append(f"  {_passage_to_citation(item)}")
            lines.append("")

        lines.append("These excerpts from the philosophical tradition provide "
                     "the basis for continued reflection on this question.")
        lines.append("")
        lines.append("[Response generated by PhiloMind pipeline. "
                     "Full LLM integration would provide a richer answer.]")

        return '\n'.join(lines)

    def _build_body(self, question: str, class_label: str,
                    passages: List[Dict]) -> str:
        if not passages:
            return ("I reflect on your question, though I find no direct passages "
                    "in the corpus to draw upon. The philosophical tradition "
                    "offers many perspectives, but none appear in the indexed texts.")

        # Collect philosophers and key sentences
        source_philosophers = []
        for p in passages:
            phil = p['source'].get('philosopher', '')
            if phil and phil not in source_philosophers and phil != 'Unknown':
                source_philosophers.append(phil)

        q_philosopher = _find_philosopher(question)
        if q_philosopher and q_philosopher in source_philosophers:
            main_phil = q_philosopher
        elif source_philosophers:
            main_phil = source_philosophers[0]
        else:
            main_phil = 'the philosophical tradition'

        best = max(passages, key=lambda p: len(p['text']))
        key_insight = _summarize_passage(
            best['text']
            .replace('...', '.')
            .replace('  ', ' '),
            max_words=40
        )

        # Build body by type
        lines = []
        if class_label == 'definition':
            lines.append(
                f"To understand this concept, we can turn to {main_phil}. "
                f"A relevant passage explains: \"{key_insight}\" "
                f"This reflects how the philosophical tradition has engaged "
                f"with this concept — not as a fixed definition, but as "
                f"a living question that each thinker addresses differently."
            )
        elif class_label == 'comparison':
            others = source_philosophers[:3]
            lines.append(
                f"The contrast between {others[0] if others else 'different thinkers'} "
                f"and other philosophical positions is instructive. "
                f"As one passage notes: \"{key_insight}\" "
                f"This illustrates the different assumptions and conclusions "
                f"that characterise philosophical disagreements."
            )
        elif class_label == 'deepening':
            lines.append(
                f"A deeper examination guided by {main_phil} reveals that "
                f"this question touches on fundamental issues. "
                f"Consider the following: \"{key_insight}\" "
                f"Going beyond surface-level answers, we see how this "
                f"inquiry connects to broader philosophical structures."
            )
        elif class_label == 'example':
            lines.append(
                f"Concrete examples from {main_phil} help illuminate this. "
                f"The text states: \"{key_insight}\" "
                f"This shows how abstract philosophical ideas manifest "
                f"in specific arguments and illustrations."
            )
        else:
            lines.append(
                f"This inquiry connects to broader themes explored by {main_phil}. "
                f"As expressed in the corpus: \"{key_insight}\" "
                f"Philosophical reflection on this topic invites us "
                f"to examine our assumptions."
            )

        return '\n\n'.join(lines)
