"""Response generator agent with source citations."""

from typing import List, Dict
from .registry import AgentRegistry


class ResponseGenerator:
    """Generates philosophical responses with source citations."""

    def __init__(self, registry: AgentRegistry):
        self.registry = registry

    def generate(self, question: str, class_label: str,
                 passages_with_sources: List[Dict],
                 philosopher: str = 'philosophy') -> str:
        expert = self.registry.get(philosopher)
        persona = expert.get_persona()
        style = persona.split('Sei ')[-1].split('.')[0] if 'Sei ' in persona else 'Socrates'

        lines = []
        lines.append(f"[Response in the style of {style}]")
        lines.append("")
        lines.append(f"On the question: \"{question}\"")
        lines.append("")

        if class_label == 'definition':
            lines.append("Let us examine what this concept truly means. "
                         "Through careful reasoning, we can discern its essential nature.")
        elif class_label == 'comparison':
            lines.append("A comparison reveals important distinctions. "
                         "Let us consider each perspective in turn.")
        elif class_label == 'example':
            lines.append("Examples illuminate abstract ideas. "
                         "Consider the following illustration.")
        elif class_label == 'indepth':
            lines.append("This question invites deeper analysis. "
                         "Let us explore its philosophical implications.")
        elif class_label == 'quiz':
            lines.append("A thoughtful question! Let me share some insights "
                         "that might help you reflect on this topic.")
        else:
            lines.append("An interesting philosophical inquiry.")

        lines.append("")

        if passages_with_sources:
            lines.append("Drawing from the philosophical corpus:")
            for i, item in enumerate(passages_with_sources, 1):
                source_info = []
                if item['source'].get('philosopher', 'Unknown') != 'Unknown':
                    source_info.append(item['source']['philosopher'])
                if item['source'].get('work', 'Unknown') != 'Unknown':
                    source_info.append(f"in \"{item['source']['work']}\"")
                if item['source'].get('subject', ''):
                    source_info.append(f"[{item['source']['subject']}]")
                source_tag = f" ({', '.join(source_info)})" if source_info else ""
                passage_text = item['text'][:200]
                lines.append(f"  [{i}]{source_tag}")
                lines.append(f"     \"{passage_text}...\"")
                if item.get('source_type') == 'teacher':
                    lines.append(f"     -> Teacher-provided material")
            lines.append("")

        lines.append("In summary, philosophical inquiry requires us to question "
                     "our assumptions and consider multiple viewpoints. "
                     "The passages above provide a starting point for reflection.")
        lines.append("")
        lines.append("[Response generated by PhiloMind pipeline. "
                     "Full LLM integration would provide a richer answer.]")

        return '\n'.join(lines)
